version: '3'

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
    networks:
      - laravel
    profiles:
      - dev
      - random

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      PMA_USER: exampleuser
      PMA_PASSWORD: examplepass
      MYSQL_ROOT_PASSWORD: rootpassword
    networks:
      - laravel
    profiles:
      - dev
      - random
    
    
  app:
    build:
      context: .
      dockerfile: laravelServiceDockerfile.txt
    container_name: laravel_app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    networks:
      - laravel
    profiles:
      - dev
      - random


  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    restart: unless-stopped
    tty: true
    ports:
      - "8000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel
    profiles:
      - random

  nginxNoRandom:
    image: nginx:stable-alpine
    container_name: nginx
    restart: unless-stopped
    tty: true
    ports:
      - "8000:80"
    volumes:
      - ./nginx/default_no_random.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel
    profiles:
      - dev

  web:
    image: python:3.9-alpine
    volumes:
      - ./randomApp:/app
    working_dir: /app
    command: python -m http.server 8000
    ports:
      - "8002:8000"
    networks:
      - laravel
    profiles:
      - random

networks:
  laravel:
    name: joel_super_secure_network
    driver: bridge


volumes:
  db_data: {}